---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "default.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "default.labels" . | indent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "default.labels" . | indent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.retry }}
