---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "default.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "default.labels" . | indent 4 }}
spec:
  ports:
    - name: {{ .Values.port.name | quote }}
      port: {{ .Values.port.number }}
      protocol: {{ .Values.service.protocol | quote }}
      targetPort: {{ .Values.port.number }}
  selector:
    {{- include "default.labels" . | indent 4 }}
  type: {{ .Values.service.type | quote }}
